#!/bin/bash
hugo --config=www.greenitglobe.com/config.toml -s www.greenitglobe.com
hugo --config=www.greenitglobe.com/config-ru.toml -s www.greenitglobe.com
hugo --config=www.greenitglobe.com/config-ar.toml -s www.greenitglobe.com
